// Categories
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';

// Posts
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const ORDER_BY = 'ORDER_BY';
